package presentation;


import presentation.image.backgroundImage;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author giba01
 */
public class mainForm extends javax.swing.JFrame {
    
static int locationWindow;
searchCustomers search = new searchCustomers();
registerCustomer register = new registerCustomer();
backgroundImage background = new backgroundImage();
    /**
     * Creates new form mainForm
     */
    public mainForm() {
        initComponents();
             
        try{  
            insertIcon();   
            dpPane.add(background); 
            background.setMaximum(true);
            background.setVisible(true);
        }catch(Exception erro){           
        }
    }
    
    
    private void close(){
        Object[] options = {"Sim","Não"};
        int answer = JOptionPane.showOptionDialog(null, "Tem certeza que deseja encerrar o programa?","Encerrar",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if(answer==0)
            dispose();
    }
    
    
    private void insertIcon() {
      try{
            setIconImage(Toolkit.getDefaultToolkit().getImage("src/images/cliente.png"));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"", "Erro",JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpPane = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        mbArchive = new javax.swing.JMenu();
        miRegisterCustomer = new javax.swing.JMenuItem();
        miConsultCustomer = new javax.swing.JMenuItem();
        jSeparator = new javax.swing.JPopupMenu.Separator();
        miClose = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Programação Visual");
        setExtendedState(MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        dpPane.setFocusCycleRoot(false);
        dpPane.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout dpPaneLayout = new javax.swing.GroupLayout(dpPane);
        dpPane.setLayout(dpPaneLayout);
        dpPaneLayout.setHorizontalGroup(
            dpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dpPaneLayout.setVerticalGroup(
            dpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        mbArchive.setText("Menu");
        mbArchive.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        miRegisterCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        miRegisterCustomer.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        miRegisterCustomer.setText("Cadastrar Cliente");
        miRegisterCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegisterCustomerActionPerformed(evt);
            }
        });
        mbArchive.add(miRegisterCustomer);

        miConsultCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        miConsultCustomer.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        miConsultCustomer.setText("Consultar Cliente");
        miConsultCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultCustomerActionPerformed(evt);
            }
        });
        mbArchive.add(miConsultCustomer);
        mbArchive.add(jSeparator);

        miClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.CTRL_MASK));
        miClose.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        miClose.setText("Fechar");
        miClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCloseActionPerformed(evt);
            }
        });
        mbArchive.add(miClose);

        jMenuBar.add(mbArchive);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCloseActionPerformed
        close();
    }//GEN-LAST:event_miCloseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        close();
    }//GEN-LAST:event_formWindowClosing

    private void miRegisterCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegisterCustomerActionPerformed
       try{
           registerCustomer.operation="cadastrar";
           dpPane.add(register);
           register.setVisible(true);
           locationWindow = 1;
           if(search.isShowing()){
               search.setLocation(420,175);
               }  
           }catch(Exception erro){
        }
    }//GEN-LAST:event_miRegisterCustomerActionPerformed

    private void miConsultCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultCustomerActionPerformed
         try{          
           dpPane.add(search);
           search.setVisible(true);
           if(register.isShowing()){
               search.setLocation(420,175);
               
           }else{
               search.setLocation(20,10);
               locationWindow = 2;
                }
           }catch(Exception erro){
       }
    }//GEN-LAST:event_miConsultCustomerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JDesktopPane dpPane;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPopupMenu.Separator jSeparator;
    private javax.swing.JMenu mbArchive;
    private javax.swing.JMenuItem miClose;
    private javax.swing.JMenuItem miConsultCustomer;
    private javax.swing.JMenuItem miRegisterCustomer;
    // End of variables declaration//GEN-END:variables

}
