package presentation;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author giba01
 */
public class progressForm extends javax.swing.JFrame {
    /**
     * Creates new form progressForm
     */
    public progressForm() 
    {
        initComponents(); 
        this.setSize(450,245);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(86,126,201));         
        
        ActionListener openMain = (ActionEvent e) -> {
            dispose();
            mainForm menu = new mainForm();
            menu.setVisible(true);
            time.stop();
            timeBar.stop();
        };
        
        ActionListener fillBar =  (ActionEvent e) -> {
            progress = progress + 100;
            pbProgress.setValue(progress);
            pbProgress.setStringPainted(true);
        };    
              time = new Timer(3000,openMain);
              time.start();  
              timeBar= new Timer(100,fillBar);
              timeBar.restart();
    }  
              
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbProgress = new javax.swing.JProgressBar();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblFormProgress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pbProgress.setMaximum(3000);
        pbProgress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(pbProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 450, 15));

        lblTitle2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(51, 51, 51));
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("Visual");
        lblTitle2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 133, 341, 57));

        lblTitle1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(51, 51, 51));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Programação");
        lblTitle1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 43, 341, 57));

        lblFormProgress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblFormProgress.setFocusable(false);
        getContentPane().add(lblFormProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(progressForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new progressForm().setVisible(true);
        });
    }
    private Timer time, timeBar;
    private int progress = 0;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFormProgress;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JProgressBar pbProgress;
    // End of variables declaration//GEN-END:variables


}
